name: Build Black Arts add-on
on:
  push:
    branches: [develop]
    paths:
      - 'submods/arkhan_black_arts/**'
      - '.github/workflows/**'
      - '.github/scripts/**'
      - '.luacheckrc'
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: black-arts-${{ github.ref }}
  cancel-in-progress: true
jobs:
  db-check:
    uses: ./.github/workflows/db-check.yml
    with:
      source_root: submods/arkhan_black_arts
  lua-check:
    uses: ./.github/workflows/lua-lint.yml
    with:
      source_root: submods/arkhan_black_arts
  build:
    needs: [db-check, lua-check]
    uses: ./.github/workflows/packfile-build.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      source_root: submods/arkhan_black_arts
      pack_name: arkhan_black_arts_TEST
      paths: |
        db/**
        text/**
        script/**
        ui/**
      game: warhammer_3
