name: Build Packfile

on: 
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
      - 'support/**'
      - 'update/**'
  
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
      - 'support/**'
      - 'update/**'
  
  workflow_dispatch:
    inputs:
      paths:
        required: false
        type: string
        default: |
          animations/** db/** script/** text/** ui/** variantmeshes/** vfx/**
        description: |
          A list of space-delimited glob patterns to include in the packfile.
      debug_enabled:
        description: Enable debug logging
        required: false
        type: boolean
        default: false

permissions:
  contents: read

concurrency:
  group: packfile-${{ github.ref }}
  cancel-in-progress: true

jobs:
  db-check:
    name: DB check
    uses: ./.github/workflows/db-check.yml
  lua-check:
    name: Lua check
    uses: ./.github/workflows/lua-lint.yml
  build-packfile-manual:
    name: Manual packfile build job
    needs: [db-check, lua-check]
    uses: ./.github/workflows/packfile-build.yml
    if: github.event_name == 'workflow_dispatch'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      paths: ${{ inputs.paths }}
      paths_separator: " "
      game: warhammer_3
      debug_enabled: ${{ inputs.debug_enabled }}
  build-packfile:
    name: Build packfile
    needs: [db-check, lua-check]
    uses: ./.github/workflows/packfile-build.yml
    if: github.event_name != 'workflow_dispatch'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      paths: |
        animations/**
        db/**
        script/**
        text/**
        ui/**
        variantmeshes/**
        vfx/**
      game: warhammer_3
